name: Cypress Testing

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      TERM: xterm-256color

    steps:
      - name: Checkouts
        uses: cypress-io/github-action@v6

      - name: Installing dependencies
        run: npm install

      - name: Executing headless cypress testing
        run: npm run e2e:deploy
