name: Cypress Testing

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      TERM: xterm-256color

    steps:
      - name: Checkouts
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: npm install

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Executing headless cypress testing
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 120
          browser: chrome
          config: defaultCommandTimeout=10000,pageLoadTimeout=60000

