name: Cypress Testing

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkouts
        uses: actions/checkout@v4

      - name: Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm install

      - name: Executing headless cypress testing
        run: npm run e2e:deploy
